[package]
name = "invaders"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bitflags = "1.3.2"
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3"
console_error_panic_hook = "0.1.7"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'console',
  'HtmlCanvasElement',
  'CanvasRenderingContext2d',
  'KeyboardEvent',
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',

]
