[package]
name = "invaders"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["console_error_panic_hook"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bitflags = "1.3.2"
wasm-bindgen = "0.2.63"
console_error_panic_hook = { version = "0.1.1", optional = true }

[dependencies.web-sys]
version = "0.3.4"
features = [
  'console',
  'HtmlCanvasElement',
  'CanvasRenderingContext2d',
  'KeyboardEvent',
  'Document',
  'Element',
  'HtmlElement',
  'Window',
]